### ISSUE TITLE
Controlling a room

### ISSUE THREAD

**Issue by CynanX** [chris1705/homebridge-lightify#3]
Hi,

Thanks for plugin, it's working well for single lights.

However, I have three bulbs assigned to a room. The Osram app. controls them all at once no problem. Apples Home app controls them individually no problem. Asking Siri to turn them on/off however and only 1/3 bulbs react.

I'm not sure if this is Apple, Homebridge or the plugin. Has anyone had any similar experiences?

Thanks,

--Cynan

**Comment by chris1705** [comment]
Hello Cynan,

did you create rooms within Apples Home App? It should work when you create your rooms and group the lights. As far as I see, it's not possible to generate rooms automatically based on the Osram Configuration.

Regards
Chris

**Comment by CynanX** [comment]
Hi Chris,

Thank you for the quick reply.

I had them grouped in the Osram app. I've just removed that grouping and then moved them all from Apples Home group from one room to another.

I've found that when two of them are in an Apple Home room they'll both switch on/off. Add the third in and then only one of them turns on/off.

I'm guessing this is an Apple issue.

--Cynan.

**Comment by gigafonzie** [comment]
Hey, I have the exact same issue.

In my setup i have a mixture of Philips Hue and Osram. In the Osram app, everything works fine and a broadcast will turn all the lights on and off. If you ask home bridge to do it, the behaviour changes depending on how many osram devices its simultaneously trying to control.

1 device = on/off is fine
2 devices = on/off is fine
3 devices = only 1 device turns on/off
5 devices = nothing turns on/off

As I said, all the osram lights work in home bridge if you control them individually, where it breaks down is when you're operating a Scene or telling Siri "all lights [in a room] on/off"

All Philips Hue devices not going through the home bridge are fine (24 devices)

Not sure its an Apple issue, but could well be!

Ben

**Comment by gigafonzie** [comment]
I'd also add that when the lights fail to turn off/on there are no errors on the Apple side of things and actually HomeKit displays the light status as if the command had executed successfully.

**Comment by chris1705** [comment]
Hi Ben,

I'm sorry you're experiencing problems with my plugin and thank you for your detailed description. 

I'm using only two devices so I can not reproduce your issue, but I may have an idea: It may be a problem with the underlaying node-lightify library I'm using for my plugin. I'll write a small script to check if it's a problem with node-lightify as soon as I'm back home.

Regards
Chris

**Comment by CynanX** [comment]
Happy to help and try out test versions if it helps!

**Comment by gigafonzie** [comment]
Me too!

**Comment by gigafonzie** [comment]
Think it might be node-lightify. I installled homeassisstant and got the same problem.

**Comment by oleg77s** [comment]
I have the same issue
6 x B40TW lights = only 1 light turns on/off
b. r.
oleg

**Comment by chris1705** [comment]
As you already guessed, it's probably a bug wihtin node-lightify. Someone already reported an issue, but the developer of node-lightify hasn't fixed it yet.. :(

**Comment by dmckillican** [comment]
![screen shot 2017-01-22 at 7 10 09 pm](https://cloud.githubusercontent.com/assets/22810092/22181025/8124f290-e0d6-11e6-9375-05da3fc14705.png)

Hi Chris,

I'm having the same issue.

An error occurs when trying to control a room or group of lamps with more than 2 lamps attached. HomeKit will control 1, or 2 lamps in a group perfectly but will not control 3 or more lamps in a group. Where 3 or more lamps are grouped, only 1 lamp responds to commands. The lamp varies each time which suggests that the node may be sending all commands at the same time, but a slight buffer may be required.

If it is possible to resolve this issue I would be very grateful.

I did note (and I don't know if this is an issue or not) that the latest version of node-lightify is 2.0.4 however 0.0.6 is also installed when installing home bridge-lightify.  Could that be a potential issue? Is the homebridge-lightify module using the latest node version?

Cheers, Drew

p.s. awesome job!

**Comment by vincentholt** [comment]
Following this. Having the same issue with more than 2 lights. I've noticed that with two lights setting levels do not always happen across both bulbs. Like the dev on this! Would love to use daily.

**Comment by apexad** [comment]
https://github.com/rainlake/homebridge-platform-lightify has been updated to be able to control groups created in the lightify app.

**Comment by mrose17** [comment]
i'm going to close this issue. it's not really clear to me that homebridge ought to be importing groups from other HA systems. @chris1705 is correct in nothing that HK has it's own grouping mechanism via rooms. that may not be adequate for your application, but that's the way HK works at present.

as @apexad notes, there's another lightify platform that does support lightify groups, so that should solve your problems!
