### ISSUE TITLE
ECONNRESET error?

### ISSUE THREAD

**Issue by djh1202** [chris1705/homebridge-lightify#4]
hi

the plugin runs great like 60% of the time, but every so often I get this error and home bridge crashes:

/usr/local/lib/node_modules/homebridge-lightify/node_modules/net-socket/index.js:80
    throw err;
    ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:544:26)

**Comment by mrose17** [comment]
there's a PR -- https://github.com/chris1705/node-lightify/pull/1 -- to a dependent library that addresses this... i've got to dash now, but ping me if you need help getting that version of the repo in your global npm area... good luck!

**Comment by djh1202** [comment]
I tried adding that but I still get this error...

**Comment by mrose17** [comment]
@djh1202 - ok, let's try an experiment. find the directory where node-lightify and net-socket are installed. then do this:

        grep ECONN net-socket/index.js

what does it say?

thanks!

**Comment by djh1202** [comment]
I get this:

    if (err.code === 'ECONNREFUSED') {

**Comment by mrose17** [comment]
ok, please edit the file and replace that one line with this:

        if (err.code === 'ECONNREFUSED' || err.code === 'ECONNRESET') {

and then restart `homebridge` ... that is what you should have gotten, i'm not sure why you didn't though...

**Comment by djh1202** [comment]
Thanks!
