### ISSUE TITLE
Using Color for tunable white

### ISSUE THREAD

**Issue by apexad** [chris1705/homebridge-lightify#6]
Checkout how it was done here:

https://github.com/lbohlmann/homebridge-lightify-tunablewhite-e14

**Comment by mrose17** [comment]
@apexad - it might be helpful to provide the context for this issue... the plugin at this repo already handles tunable white bulbs mapping hue/sat to a temperature, cf., the `setK` method defined at https://github.com/chris1705/homebridge-lightify/blob/master/index.js#L240

thanks!

**Comment by apexad** [comment]
With this plugin, the Home app allows only for brightness and on/off. However, the referenced plugin adds a Color option to the Home app for tunable whites.

Is there a HomeKit app that actually allows you to use anything other than brightness and on/off with this plugin?

**Comment by mrose17** [comment]
both plugins export the same characteristics: On, Brightness, Hue, and Saturation.

my recommendation is the elgato eve app. here is what i see from that:

![img_0367](https://cloud.githubusercontent.com/assets/400552/23435092/b426a772-fdbb-11e6-886a-9cc07d38685a.jpg)

**Comment by mrose17** [comment]
sorry, github is having S3 issues... two more files to upload.

**Comment by mrose17** [comment]
![img_0366](https://cloud.githubusercontent.com/assets/400552/23435519/8b71a1be-fdbc-11e6-8c16-3b3bc78c4004.jpg)

**Comment by mrose17** [comment]
note the color above ^^^

**Comment by mrose17** [comment]
![img_0365](https://cloud.githubusercontent.com/assets/400552/23435586/ad8b7f40-fdbc-11e6-9a82-faf52dcb2d59.jpg)

**Comment by mrose17** [comment]
in general, it'd be better to select the "WHITE" tab on the right which will show color temperatures...

**Comment by apexad** [comment]
Are you sure you have Tunable whites? Different than the RGBW lights.
I have Eve app (and tested in it before making this issue), and it does not show color for Tunable Whites with this plugin. Eve recognizes color only, same as the Home app.

The plugin I referenced ignores color is not supported for Tunable whites and instead makes the temperature changes available via a color picker, and it works in the Apple Home app too.

Tunable White
https://www.amazon.com/dp/B00R3ID2BG/ref=cm_sw_r_sms_c_api_HnGTybJ7WX7DD
RGBW
https://www.amazon.com/dp/B0197840KQ/ref=cm_sw_r_sms_c_api_MoGTyb8B91JQV

**Comment by mrose17** [comment]
perhaps that is the problem. the bulbs i am using are identified by this:

    (!lightify.isColorSupported(this.props.type)) && (lightify.isTemperatureSupported(this.props.type))

my guess is that the bulbs you are using fail this test and so are marked as brightness only.

ok, in order to get to the bottom of this, we are going to need to find out what `type` the bulbs are being reported as.  the easiest way to do this is to go to the other plugin and look for a line like this:

          console.log("Requesting Status of " + this.name);

underneath it, put this

            console.lo('builb type=" this.type)

and then let me know what it says when you run it.

thanks!

**Comment by apexad** [comment]
Looking at the source code of node-lightify, I am guessing type is 2 (versus 10 for RGBW) but you are missing the point. Current Home Kit apps allow you to change Color only, not Temperature (or at least not Temperature independent of Color). The referenced plugin at the beginning of this issue hacks homebridge/HomeKit and exposes Temperature changes as Color changes, thus allowing Tunable Whites to be changed via the current HomeKit apps.

Edit: Tunable Whites are likely type 2, RGBW is type 10.

**Comment by apexad** [comment]
![img_0918](https://cloud.githubusercontent.com/assets/1437332/23440195/d7d167a4-fdd7-11e6-8476-35728f3604f2.PNG)

Lightify app has 3 rings, Temperature, Brightness, and Color. You can see for this light, Color is blacked out, but Temperature and Brightness is not.

**Comment by mrose17** [comment]
here is what i get with my bulbs:

    {
      "id": 49184,
      "mac": 1.868171230834817e-308,
      "type": 2,
      "firmware_version": 0,
      "online": 2,
      "groupid": 0,
      "status": 0,
      "brightness": 100,
      "temperature": 2688,
      "red": 1,
      "green": 0,
      "blue": 0,
      "alpha": 255,
      "name": "Hallway"
    }

it says the type is '2' and it all works the way i think it should.

could you do something with your bulbs? i modified node-lightify/index.js, in the discovery function to get that output.

with respect to what's going on in this plugin: homekit doesn't "do" color temperature, it does hue and saturation.

both plugins map from the hue/sat provided by homekit into a color temperature and then makes a call to `lightify.node_temperature` to effect the change.

there is a difference in the formula used to convert back and forth between the two plugins. the other difference is that this plugin looks at the bulb type to determine whether it can use temperature.

this brings us back to the question: what is the `type` of the bulbs you are using?

thanks,

/mtr

**Comment by apexad** [comment]
I modified `node-lightify` and my bulbs are definitely coming back as type 2.

I cleared homebridge/persist and /accessories and restarted homebridge, still just seeing Off and Brightness in Eve App.

**Comment by apexad** [comment]
I figured it out!
you need to bump the version to 0.0.10
all the commits past the version bump to 0.0.9 are not getting download with `npm install homebridge-lightify`
Had to to `npm install https://github.com/chris1705/homebridge-lightify.git` and now I have color.
