### ISSUE TITLE
Q: can someone recommend a lightify-compatible color bulb

### ISSUE THREAD

**Issue by mrose17** [chris1705/homebridge-lightify#9]
that i an purchase at amazon-US to test adding color support to the plugin?

thanks!

cc: @apexad

**Comment by apexad** [comment]
Don't have any color bulbs myself.  However, just so you know from what I can tell this plugin is abandoned.  

https://www.npmjs.com/package/homebridge-platform-lightify is being actively developed, and has passed this version in many ways now.

**Comment by mrose17** [comment]
thanks. i found a bulb on amazon and did an update. i'll review the other plugin as well.. thanks!
